language: generic

before_install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_0.57.2_Linux-64bit.deb
  - sudo dpkg -i hugo_0.57.2_Linux-64bit.deb

install:
  - hugo env
  - hugo

branches:
  only:
    - master
