baseURL = "http://pirzy.com/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Devenir Simplement Meilleur"
theme = "manis"

# Copyright notice. Note: You can use HTML tag here
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`
copyright = "&copy; <a href='https://pierrehenry.be'>Pierre-Henry Soria</a>, {year}"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 16

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[menu]
	[[menu.main]]
		name = "Post"
		url = "/post/"

	[[menu.main]]
		name = "About"
		url = "/about"

[taxonomies]
	tag = "tags"
	category = "categories"
	author = "authors"

[permalinks]
    posts = "/:year/:slug"

[params]
    author = "Pierre-Henry Soria"
	# If false, use minified CSS (ui.min.css)
	debugCSS = false
	# Custom CSS
	customCSS = []

	# List of sections that support disqus comments
	disqusSections = [ "blog" ]
	# Site meta description
	description = "Pirzy.com - Devenir Simplement Meilleur"
	# Site's Tagline (Subtitle or Keyword)
	tagline = "Devenir Meilleur, Savoir Plus, chaque jour 🥇"
	# If true give attribution to this theme
	themeAttrib = false

	# Configure which sections for Latest Posts
	mainSections = ["blog", "post"]

	# Color of your website's accent
	colorTheme = "#ff6565"
	# Maximum number of item in Latest Posts or Works
	latestCount = 3
	# Path to site's favicon image
	faviconImg = ""
	# Date format in item list
	dateFmt = "02 Jan 2006"

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "pierre@soria.email"
	github = "https://github.com/pH-7/"
	twitter = "https://twitter.com/phenrysay"


[languages.in]
	lang = "fr"
	languageName = "Français"
	weight = 1
